import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Josefin_Sans, Sawarabi_Gothic } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import TopBar from "./UI/TopBar";
import Footer from "./UI/Footer";
//import { josefin_sans, sawarabi_gothic } from "./UI/fonts";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

const josefin_sans = Josefin_Sans({
  variable: "--font-josefin_sans",
  subsets: ["latin"],
});

const sawarabi_gothic = Sawarabi_Gothic({
  variable: "--font-sawarabi_gothic",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>Blog</title>
      </head>
      <body className={`${josefin_sans.className} antialiased bg-gray-100`}>
        <TopBar />
        <main className="min-h-screen w-full max-w-[1000px] mx-auto  bg-white p-6 border border-gray-200 shadow-s">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
